#!/usr/bin/env python3
import sys
import os

GAME_DIR = './ggj'

sys.path.append(GAME_DIR)
os.chdir(GAME_DIR)

if __name__ == '__main__':
    from ggj.custom_game import CustomGame
    g = CustomGame()
    g.run()
