#!/usr/bin/env python
import sys
import os

# import pygame_sdl2
# pygame_sdl2.import_as_pygame()

GAME_DIR = './ggj'

sys.path.append(GAME_DIR)
os.chdir(GAME_DIR)

if __name__ == '__main__':
    from ggj.custom_game import CustomGame
    g = CustomGame()
    g.run()
